openapi: 3.0.1
info:
  title: An empty API spec
  version: "1.2.0-draft.1"
  contact: 
    name: "The team name going to implement this spec"
    url: "https://github.com/test-owner/actual-api-implementation-repository"
tags: 
  - name: Sample Resource
    description: "Sample Resource description"
paths: {}
components:
  schemas: {}